### ISSUE TITLE
recover from failure instead of panic?

### ISSUE THREAD

**Issue by TomPridham** [cfsamson/powershell-script#1]
does the crate have to panic if it can't get a handle to stdin? i'd like to use this, but panicking isn't acceptable in my use case

**Comment by cfsamson** [comment]
No there is no good reason to not make that an recoverable error. I made a quick fix for it. Take a look at the current master. You can try it out by pulling the crate from `git=https://github.com/cfsamson/powershell-script/i` in `Cargo.toml`.

**Comment by cfsamson** [comment]
@TomPridham If you get the chance to test it and it works for your needs let me know and I’ll publish an update to crates.io.

**Comment by TomPridham** [comment]
I'll test it tonight and let you know. Thanks for the quick response!

**Comment by TomPridham** [comment]
im not sure how to test if it can't get a handle, but it seems to be working for me! thanks for the fix

**Comment by cfsamson** [comment]
Crates.io package is now updated.
