### ISSUE TITLE
Is there some way to run a .ps1 script?

### ISSUE THREAD

**Issue by Hellager** [cfsamson/powershell-script#12]
I have a list.ps1 script, here's the code
```powershell
$Namespace = "shell:::{679f85cb-0220-4080-b29b-5540cc05aab6}"
$QuickAccess = New-Object -ComObject Shell.Application
$RecentFiles = $QuickAccess.Namespace($Namespace).Items()

foreach ($item in $RecentFiles)
{
	Write-Output $item.Path
}
```
I'm able to directly run it when call `./list.ps1` in powershell, output serveral path strings.
Failed to run it like what the docs did.
```rust
    let list_quick_access = include_str!("./scripts/list.ps1");
    match powershell_script::run(list_quick_access) {
        Ok(output) => {
            println!("{:?}", output);
        }
        Err(e) => {
            println!("Error: {}", e)
        }
    }
```
Is this crate able to run .ps1 file now? or some ways to run the code and get the output.

**Comment by cfsamson** [comment]
Yeah, I think the problem is that I run every line as a powershell command so the `foreach` block doesn't run properly. I'm not on a Windows machine right now but you can try this simple workaround:

```ps
$Namespace = "shell:::{679f85cb-0220-4080-b29b-5540cc05aab6}"
$QuickAccess = New-Object -ComObject Shell.Application
$RecentFiles = $QuickAccess.Namespace($Namespace).Items()

foreach ($item in $RecentFiles) { Write-Output $item.Path }
```

The problem is probably fixable by doing some changes to how I pipe out the commands I just haven't had the need for it (until you made me aware of it).

**Comment by Hellager** [comment]
Thanks for your help. Now it works well.
I believe it's nice to make it possiable to run with scripts wrting with blocks, especially poweshell is capable to define functions.
