### ISSUE TITLE
The website https://cfsamson.github.io cannot be accessed

### ISSUE THREAD

**Issue by bestgopher** [cfsamson/powershell-script#15]
I'm sorry for the inconvenience. I'd like to ask where I can browse your articles, as it seems that the previous website is inaccessible

https://cfsamson.github.io/books-futures-explained/introduction.html

**Comment by cfsamson** [comment]
Hi, and no problem. Sorry for having to take those links down. I'm currently working on a "proper" book covering the article/book you linked to and some of the other smaller books I've written with some updated content. I will make a proper book out of it, I can't publish overlapping material myself at the same time.

Sorry about that.
